//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.15 at 09:53:20 AM IST 
//


package com.finflux.risk.creditbureau.provider.highmark.xsd.old.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="INQUIRY-UNIQUE-REF-NO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="REQUEST-DT-TM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inquiryuniquerefno",
    "requestdttm"
})
@XmlRootElement(name = "INQUIRY")
public class INQUIRYAT02 {

    @XmlElement(name = "INQUIRY-UNIQUE-REF-NO", required = true)
    protected String inquiryuniquerefno;
    @XmlElement(name = "REQUEST-DT-TM", required = true)
    protected String requestdttm;

    /**
     * Gets the value of the inquiryuniquerefno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINQUIRYUNIQUEREFNO() {
        return inquiryuniquerefno;
    }

    /**
     * Sets the value of the inquiryuniquerefno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINQUIRYUNIQUEREFNO(String value) {
        this.inquiryuniquerefno = value;
    }

    /**
     * Gets the value of the requestdttm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREQUESTDTTM() {
        return requestdttm;
    }

    /**
     * Sets the value of the requestdttm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREQUESTDTTM(String value) {
        this.requestdttm = value;
    }

}
