//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.08 at 07:33:26 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://services.equifax.com/eport/ws/schemas/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.finflux.risk.creditbureau.provider.equifax.xsd;
