INSERT IGNORE INTO `m_permission` (`grouping`, `code`, `entity_name`, `action_name`, `can_maker_checker`) VALUES 
('task', 'CREATE_TASK_CONFIG', 'TASK_CONFIG', 'CREATE', 0),
('task', 'CREATE_TASK_CONFIG_CHECKER', 'TASK_CONFIG', 'CREATE_CHECKER', 0),
('task', 'UPDATE_TASK_CONFIG', 'TASK_CONFIG', 'UPDATE', 0),
('task', 'UPDATE_TASK_CONFIG_CHECKER', 'TASK_CONFIG', 'UPDATE_CHECKER', 0),
('task', 'ACTIVATE_TASK_CONFIG', 'TASK_CONFIG', 'ACTIVATE', 0),
('task', 'ACTIVATE_TASK_CONFIG_CHECKER', 'TASK_CONFIG', 'ACTIVATE_CHECKER', 0),
('task', 'INACTIVATE_TASK_CONFIG', 'TASK_CONFIG', 'INACTIVATE', 0),
('task', 'INACTIVATE_TASK_CONFIG_CHECKER', 'TASK_CONFIG', 'INACTIVATE_CHECKER', 0),
('task', 'DELETE_TASK_CONFIG', 'TASK_CONFIG', 'DELETE', 0),
('task', 'DELETE_TASK_CONFIG_CHECKER', 'TASK_CONFIG', 'DELETE_CHECKER', 0),
('task', 'READ_TASK_CONFIG', 'TASK_CONFIG', 'READ', 0);