INSERT IGNORE INTO `f_task_activity` (`name`, `identifier`, `config_values`, `supported_actions`, `type`) VALUES ('Adhoc', 'adhoc', NULL, NULL, 3),
('Bank Transaction', 'banktransaction', NULL, NULL, 3),
('Credit Bureau', 'creditbureau', NULL, NULL, 3),
('Datatable Task', 'datatable', NULL, NULL, 2),
('Existing Loans', 'existingloans', NULL, NULL, 3),
('Upload Document', 'clientdocument', NULL, NULL, 3),
('Survey Task', 'survey', NULL, NULL, 1),
('Loan Application Approval', 'loanapplicationapproval', NULL, NULL, 3),
('Loan Disbursal', 'loanapplicationdisbursal', NULL, NULL, 3),
('Bank Account', 'bankaccount', NULL, NULL, 3),
('KYC', 'kyc', NULL, NULL, 3),
('Client DeDuplication', 'clientdeduplication', NULL, NULL, 3),
('Address Activity', 'address', NULL, NULL, 3),
('Family Details Activity', 'familydetails', NULL, NULL, 3),
('Client Activation Activity', 'clientActivation', NULL, NULL, 3);
