CREATE TABLE `f_voucher_details` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`voucher_number` VARCHAR(50) NOT NULL,
	`voucher_type` INT(2) NOT NULL, 
	`jentry_id` BIGINT(20),
	`amount` DECIMAL(19,6) NOT NULL,
	`financial_year` VARCHAR(10) NOT NULL,
	`related_voucher_id` BIGINT(20) NULL DEFAULT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `FK1_voucher_journal_id` FOREIGN KEY (`jentry_id`) REFERENCES `f_journal_entry` (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

ALTER TABLE `m_payment_detail`
	ADD COLUMN `branch_name` VARCHAR(200) NULL AFTER `bank_number`,
	ADD COLUMN `payment_date` DATE NULL DEFAULT NULL AFTER `routing_code`;

INSERT IGNORE INTO `m_permission` (`grouping`, `code`, `entity_name`, `action_name`, `can_maker_checker`) VALUES 
('portfolio', 'CREATE_CASHPAYMENT_VOUCHER', 'CASHPAYMENT_VOUCHER', 'CREATE', 0),
('portfolio', 'CREATE_CASHPAYMENT_VOUCHER_CHECKER', 'CASHPAYMENT_VOUCHER', 'CREATE_CHECKER', 0),
('portfolio', 'UPDATE_CASHPAYMENT_VOUCHER', 'CASHPAYMENT_VOUCHER', 'UPDATE', 0),
('portfolio', 'UPDATE_CASHPAYMENT_VOUCHER_CHECKER', 'CASHPAYMENT_VOUCHER', 'UPDATE_CHECKER', 0),
('portfolio', 'REVERSE_CASHPAYMENT_VOUCHER', 'CASHPAYMENT_VOUCHER', 'REVERSE', 0),
('portfolio', 'REVERSE_CASHPAYMENT_VOUCHER_CHECKER', 'CASHPAYMENT_VOUCHER', 'REVERSE_CHECKER', 0),
('portfolio', 'READ_CASHPAYMENT_VOUCHER', 'CASHPAYMENT_VOUCHER', 'READ', 0);

INSERT IGNORE INTO `m_permission` (`grouping`, `code`, `entity_name`, `action_name`, `can_maker_checker`) VALUES 
('portfolio', 'CREATE_CASHRECEIPT_VOUCHER', 'CASHRECEIPT_VOUCHER', 'CREATE', 0),
('portfolio', 'CREATE_CASHRECEIPT_VOUCHER_CHECKER', 'CASHRECEIPT_VOUCHER', 'CREATE_CHECKER', 0),
('portfolio', 'UPDATE_CASHRECEIPT_VOUCHER', 'CASHRECEIPT_VOUCHER', 'UPDATE', 0),
('portfolio', 'UPDATE_CASHRECEIPT_VOUCHER_CHECKER', 'CASHRECEIPT_VOUCHER', 'UPDATE_CHECKER', 0),
('portfolio', 'REVERSE_CASHRECEIPT_VOUCHER', 'CASHRECEIPT_VOUCHER', 'REVERSE', 0),
('portfolio', 'REVERSE_CASHRECEIPT_VOUCHER_CHECKER', 'CASHRECEIPT_VOUCHER', 'REVERSE_CHECKER', 0),
('portfolio', 'READ_CASHRECEIPT_VOUCHER', 'CASHRECEIPT_VOUCHER', 'READ', 0);

INSERT IGNORE INTO `m_permission` (`grouping`, `code`, `entity_name`, `action_name`, `can_maker_checker`) VALUES 
('portfolio', 'CREATE_BANKPAYMENT_VOUCHER', 'BANKPAYMENT_VOUCHER', 'CREATE', 0),
('portfolio', 'CREATE_BANKPAYMENT_VOUCHER_CHECKER', 'BANKPAYMENT_VOUCHER', 'CREATE_CHECKER', 0),
('portfolio', 'UPDATE_BANKPAYMENT_VOUCHER', 'BANKPAYMENT_VOUCHER', 'UPDATE', 0),
('portfolio', 'UPDATE_BANKPAYMENT_VOUCHER_CHECKER', 'BANKPAYMENT_VOUCHER', 'UPDATE_CHECKER', 0),
('portfolio', 'REVERSE_BANKPAYMENT_VOUCHER', 'BANKPAYMENT_VOUCHER', 'REVERSE', 0),
('portfolio', 'REVERSE_BANKPAYMENT_VOUCHER_CHECKER', 'BANKPAYMENT_VOUCHER', 'REVERSE_CHECKER', 0),
('portfolio', 'READ_BANKPAYMENT_VOUCHER', 'BANKPAYMENT_VOUCHER', 'READ', 0);

INSERT IGNORE INTO `m_permission` (`grouping`, `code`, `entity_name`, `action_name`, `can_maker_checker`) VALUES 
('portfolio', 'CREATE_BANKRECEIPT_VOUCHER', 'BANKRECEIPT_VOUCHER', 'CREATE', 0),
('portfolio', 'CREATE_BANKRECEIPT_VOUCHER_CHECKER', 'BANKRECEIPT_VOUCHER', 'CREATE_CHECKER', 0),
('portfolio', 'UPDATE_BANKRECEIPT_VOUCHER', 'BANKRECEIPT_VOUCHER', 'UPDATE', 0),
('portfolio', 'UPDATE_BANKRECEIPT_VOUCHER_CHECKER', 'BANKRECEIPT_VOUCHER', 'UPDATE_CHECKER', 0),
('portfolio', 'REVERSE_BANKRECEIPT_VOUCHER', 'BANKRECEIPT_VOUCHER', 'REVERSE', 0),
('portfolio', 'REVERSE_BANKRECEIPT_VOUCHER_CHECKER', 'BANKRECEIPT_VOUCHER', 'REVERSE_CHECKER', 0),
('portfolio', 'READ_BANKRECEIPT_VOUCHER', 'BANKRECEIPT_VOUCHER', 'READ', 0);

INSERT IGNORE INTO `m_permission` (`grouping`, `code`, `entity_name`, `action_name`, `can_maker_checker`) VALUES 
('portfolio', 'CREATE_INTERBRANCHCASHTRANSFER_VOUCHER', 'INTERBRANCHCASHTRANSFER_VOUCHER', 'CREATE', 0),
('portfolio', 'CREATE_INTERBRANCHCASHTRANSFER_VOUCHER_CHECKER', 'INTERBRANCHCASHTRANSFER_VOUCHER', 'CREATE_CHECKER', 0),
('portfolio', 'UPDATE_INTERBRANCHCASHTRANSFER_VOUCHER', 'INTERBRANCHCASHTRANSFER_VOUCHER', 'UPDATE', 0),
('portfolio', 'UPDATE_INTERBRANCHCASHTRANSFER_VOUCHER_CHECKER', 'INTERBRANCHCASHTRANSFER_VOUCHER', 'UPDATE_CHECKER', 0),
('portfolio', 'REVERSE_INTERBRANCHCASHTRANSFER_VOUCHER', 'INTERBRANCHCASHTRANSFER_VOUCHER', 'REVERSE', 0),
('portfolio', 'REVERSE_INTERBRANCHCASHTRANSFER_VOUCHER_CHECKER', 'INTERBRANCHCASHTRANSFER_VOUCHER', 'REVERSE_CHECKER', 0),
('portfolio', 'READ_INTERBRANCHCASHTRANSFER_VOUCHER', 'INTERBRANCHCASHTRANSFER_VOUCHER', 'READ', 0);

INSERT IGNORE INTO `m_permission` (`grouping`, `code`, `entity_name`, `action_name`, `can_maker_checker`) VALUES 
('portfolio', 'CREATE_INTERBRANCHBANKTRANSFER_VOUCHER', 'INTERBRANCHBANKTRANSFER_VOUCHER', 'CREATE', 0),
('portfolio', 'CREATE_INTERBRANCHBANKTRANSFER_VOUCHER_CHECKER', 'INTERBRANCHBANKTRANSFER_VOUCHER', 'CREATE_CHECKER', 0),
('portfolio', 'UPDATE_INTERBRANCHBANKTRANSFER_VOUCHER', 'INTERBRANCHBANKTRANSFER_VOUCHER', 'UPDATE', 0),
('portfolio', 'UPDATE_INTERBRANCHBANKTRANSFER_VOUCHER_CHECKER', 'INTERBRANCHBANKTRANSFER_VOUCHER', 'UPDATE_CHECKER', 0),
('portfolio', 'REVERSE_INTERBRANCHBANKTRANSFER_VOUCHER', 'INTERBRANCHBANKTRANSFER_VOUCHER', 'REVERSE', 0),
('portfolio', 'REVERSE_INTERBRANCHBANKTRANSFER_VOUCHER_CHECKER', 'INTERBRANCHBANKTRANSFER_VOUCHER', 'REVERSE_CHECKER', 0),
('portfolio', 'READ_INTERBRANCHBANKTRANSFER_VOUCHER', 'INTERBRANCHBANKTRANSFER_VOUCHER', 'READ', 0);

INSERT IGNORE INTO `m_permission` (`grouping`, `code`, `entity_name`, `action_name`, `can_maker_checker`) VALUES 
('portfolio', 'CREATE_CONTRAENTRY_VOUCHER', 'CONTRAENTRY_VOUCHER', 'CREATE', 0),
('portfolio', 'CREATE_CONTRAENTRY_VOUCHER_CHECKER', 'CONTRAENTRY_VOUCHER', 'CREATE_CHECKER', 0),
('portfolio', 'UPDATE_CONTRAENTRY_VOUCHER', 'CONTRAENTRY_VOUCHER', 'UPDATE', 0),
('portfolio', 'UPDATE_CONTRAENTRY_VOUCHER_CHECKER', 'CONTRAENTRY_VOUCHER', 'UPDATE_CHECKER', 0),
('portfolio', 'REVERSE_CONTRAENTRY_VOUCHER', 'CONTRAENTRY_VOUCHER', 'REVERSE', 0),
('portfolio', 'REVERSE_CONTRAENTRY_VOUCHER_CHECKER', 'CONTRAENTRY_VOUCHER', 'REVERSE_CHECKER', 0),
('portfolio', 'READ_CONTRAENTRY_VOUCHER', 'CONTRAENTRY_VOUCHER', 'READ', 0);

INSERT IGNORE INTO `m_permission` (`grouping`, `code`, `entity_name`, `action_name`, `can_maker_checker`) VALUES 
('portfolio', 'CREATE_JVENTRY_VOUCHER', 'JVENTRY_VOUCHER', 'CREATE', 0),
('portfolio', 'CREATE_JVENTRY_VOUCHER_CHECKER', 'JVENTRY_VOUCHER', 'CREATE_CHECKER', 0),
('portfolio', 'UPDATE_JVENTRY_VOUCHER', 'JVENTRY_VOUCHER', 'UPDATE', 0),
('portfolio', 'UPDATE_JVENTRY_VOUCHER_CHECKER', 'JVENTRY_VOUCHER', 'UPDATE_CHECKER', 0),
('portfolio', 'REVERSE_JVENTRY_VOUCHER', 'JVENTRY_VOUCHER', 'REVERSE', 0),
('portfolio', 'REVERSE_JVENTRY_VOUCHER_CHECKER', 'JVENTRY_VOUCHER', 'REVERSE_CHECKER', 0),
('portfolio', 'READ_JVENTRY_VOUCHER', 'JVENTRY_VOUCHER', 'READ', 0);
