ALTER TABLE f_task_config_entity_type_mapping ADD COLUMN `is_active` TINYINT(1) NOT NULL DEFAULT 1;

INSERT IGNORE INTO m_permission (`grouping`,`code`,`entity_name`,`action_name`,`can_maker_checker`) 
 VALUES ('task','CREATE_TASK_CONFIG_ENTITYMAPPING','TASK_CONFIG_ENTITYMAPPING','CREATE',0),
 ('task','CREATE_TASK_CONFIG_ENTITYMAPPING_CHECKER','TASK_CONFIG_ENTITYMAPPING','CREATE_CHECKER',0),
 ('task','UPDATE_TASK_CONFIG_ENTITYMAPPING','TASK_CONFIG_ENTITYMAPPING','UPDATE',0),
 ('task','UPDATE_TASK_CONFIG_ENTITYMAPPING_CHECKER','TASK_CONFIG_ENTITYMAPPING','UPDATE_CHECKER',0),
 ('task','DELETE_TASK_CONFIG_ENTITYMAPPING','TASK_CONFIG_ENTITYMAPPING','DELETE',0),
 ('task','DELETE_TASK_CONFIG_ENTITYMAPPING_CHECKER','TASK_CONFIG_ENTITYMAPPING','DELETE_CHECKER',0),
 ('task','INACTIVATE_TASK_CONFIG_ENTITYMAPPING','TASK_CONFIG_ENTITYMAPPING','INACTIVATE',0),
 ('task','INACTIVATE_TASK_CONFIG_ENTITYMAPPING_CHECKER','TASK_CONFIG_ENTITYMAPPING','INACTIVATE_CHECKER',0),
 ('task','READ_TASK_CONFIG_ENTITYMAPPING','TASK_CONFIG_ENTITYMAPPING','READ',0);