INSERT IGNORE INTO `stretchy_report` (`report_name`, `report_type`, `report_subtype`, `report_category`, `report_sql`, `description`, `core_report`, `use_report`, `track_usage`) VALUES 
('Client Created', 'SMS', 'Triggered', 'Clients', 'SELECT mc.display_name AS name, mo.name AS branch, mc.external_id AS externalid, mc.mobile_no AS mobileNo\nFROM m_client mc\nJOIN m_office mo ON mc.office_id = mo.id\nWHERE mc.id = ${clientId}', 'Report for client details based on ID', 0, 1, 0),
('Savings Closed', 'SMS', 'Triggered', 'Savings', 'SELECT \r\nc.id AS "id",\r\nc.firstname AS "firstName",\r\nc.middlename AS "middleName",\r\nc.lastname AS "lastName",\r\nc.display_name AS "fullName",\r\nc.mobile_no AS "mobileNo",\r\ns.account_no AS "savingsAccountNo",\r\nounder.id AS "officeNumber",\r\nounder.name AS "officeName",\r\ns.account_balance_derived AS "amount"\r\n\r\nFROM m_office o\r\nJOIN m_office ounder ON ounder.hierarchy LIKE CONCAT(o.hierarchy, \'%\')\r\nJOIN m_client c ON c.office_id = ounder.id\r\nJOIN m_savings_account s ON s.client_id = c.id\r\nJOIN m_savings_product sp ON sp.id = s.product_id\r\nLEFT JOIN m_staff st ON st.id = s.field_officer_id\r\nLEFT JOIN m_currency cur ON cur.code = s.currency_code\r\nWHERE o.id = ${officeId} AND (IFNULL(s.field_officer_id, -10) = ${loanOfficerId} OR "-1" = ${loanOfficerId}) AND s.id = ${savingsId}', 'Savings Closed', 0, 1, 0),
('Loan Disbursed', 'SMS', 'Triggered', NULL, 'SELECT mc.id, mc.firstname, mc.middlename as middlename, mc.lastname, mc.display_name as FullName, mc.mobile_no as mobileNo, mc.group_name as GroupName, mo.name as officename, ml.id as loanId, ml.account_no as accountnumber, ml.principal_amount_proposed as loanamount, ml.annual_nominal_interest_rate as annualinterestrate FROM m_office mo JOIN m_office ounder ON ounder.hierarchy LIKE CONCAT(mo.hierarchy, \'%\') AND ounder.hierarchy like CONCAT(\'.\', \'%\') LEFT JOIN ( select  ml.id as loanId,  ifnull(mc.id,mc2.id) as id,  ifnull(mc.firstname,mc2.firstname) as firstname,  ifnull(mc.middlename,ifnull(mc2.middlename,(\'\'))) as middlename,  ifnull(mc.lastname,mc2.lastname) as lastname,  ifnull(mc.display_name,mc2.display_name) as display_name,  ifnull(mc.status_enum,mc2.status_enum) as status_enum, ifnull(mc.mobile_no,mc2.mobile_no) as mobile_no, ifnull(mg.office_id,mc2.office_id) as office_id, ifnull(mg.staff_id,mc2.staff_id) as staff_id, mg.id as group_id, mg.display_name as group_name from m_loan ml left join m_group mg on mg.id = ml.group_id left join m_group_client mgc on mgc.group_id = mg.id left join m_client mc on mc.id = mgc.client_id left join m_client mc2 on mc2.id = ml.client_id order by loanId ) mc on mc.office_id = ounder.id  left join m_loan ml on ml.id = mc.loanId WHERE mc.status_enum = 300 and mc.mobile_no is not null and (mo.id = ${officeId} or ${officeId} = -1) and (mc.staff_id = ${loanOfficerId} or ${loanOfficerId} = -1)and (ml.id = ${loanId} or ${loanId} = -1)and (mc.id = ${clientId} or ${clientId} = -1)and (mc.group_id = ${groupId} or ${groupId} = -1)and (ml.loan_type_enum = ${loanType} or ${loanType} = -1)', 'Loan and client data of approved loan', 0, 0, 0);

INSERT IGNORE INTO `stretchy_report_parameter` (`report_id`, `parameter_id`, `report_parameter_name`) VALUES 
((SELECT id FROM stretchy_report WHERE report_name = 'Client Created'), (SELECT id FROM stretchy_parameter WHERE parameter_name = 'DefaultClient'), 'clientId'),
((SELECT id FROM stretchy_report WHERE report_name = 'Savings Closed'), (SELECT id FROM stretchy_parameter WHERE parameter_name = 'OfficeIdSelectOne'), 'officeId'),
((SELECT id FROM stretchy_report WHERE report_name = 'Savings Closed'), (SELECT id FROM stretchy_parameter WHERE parameter_name = 'loanOfficerIdSelectAll'), 'loanOfficerId'),
((SELECT id FROM stretchy_report WHERE report_name = 'Savings Closed'), (SELECT id FROM stretchy_parameter WHERE parameter_name = 'DefaultSavings'), 'savingsId'),
((SELECT id FROM stretchy_report WHERE report_name = 'Loan Disbursed'), (SELECT id FROM stretchy_parameter WHERE parameter_name = 'OfficeIdSelectOne'), 'officeId'),
((SELECT id FROM stretchy_report WHERE report_name = 'Loan Disbursed'), (SELECT id FROM stretchy_parameter WHERE parameter_name = 'loanOfficerIdSelectAll'), 'loanOfficerId'),
((SELECT id FROM stretchy_report WHERE report_name = 'Loan Disbursed'), (SELECT id FROM stretchy_parameter WHERE parameter_name = 'DefaultLoan'), 'loanId'),
((SELECT id FROM stretchy_report WHERE report_name = 'Loan Disbursed'), (SELECT id FROM stretchy_parameter WHERE parameter_name = 'DefaultClient'), 'clientId'),
((SELECT id FROM stretchy_report WHERE report_name = 'Loan Disbursed'), (SELECT id FROM stretchy_parameter WHERE parameter_name = 'DefaultGroup'), 'groupId'),
((SELECT id FROM stretchy_report WHERE report_name = 'Loan Disbursed'), (SELECT id FROM stretchy_parameter WHERE parameter_name = 'SelectLoanType'), 'loanType');

INSERT IGNORE INTO `m_permission` (`grouping`, `code`, `entity_name`, `action_name`, `can_maker_checker`) VALUES 
('report', 'READ_Client Created', 'Client Created', 'READ', 0),
('report', 'READ_Savings Closed', 'Savings Closed', 'READ', 0),
('report', 'READ_Loan Disbursed', 'Loan Disbursed', 'READ', 0);


INSERT INTO `sms_campaign` (`campaign_name`, `campaign_type`, `campaign_trigger_type`, `report_id`, `provider_id`, `param_value`, `status_enum`, `message`, `closedon_date`, `closedon_userid`, `submittedon_date`, `submittedon_userid`, `approvedon_date`, `approvedon_userid`, `recurrence`, `next_trigger_date`, `last_trigger_date`, `recurrence_start_date`, `is_visible`) VALUES 
('Client Created', 1, 3, (SELECT id FROM stretchy_report WHERE report_name = 'Client Created'), 1, '{"reportName":"Client Created"}', 300, 'Dear {{name}}, welcome to {{branch}}, your member no is {{externalid}} . Have a blessed day.', NULL, NULL, CURDATE(), 1, CURDATE(), 1, NULL, NULL, NULL, NOW(), 1),
('Savings Closed', 1, 3, (SELECT id FROM stretchy_report WHERE report_name = 'Savings Closed'), 1, '{"officeId":1,"loanOfficerId":-1,"reportName":"Savings Closed"}', 300, 'Dear {{fullName}}, your account has been closed, collect your savings of {{amount}} . {{officeName}}', NULL, NULL, CURDATE(), 1, CURDATE(), 1, NULL, NULL, NULL, NOW(), 1),
('Loan Disbursed', 1, 3, (SELECT id FROM stretchy_report WHERE report_name = 'Loan Disbursed'), 1, '{"officeId":1,"loanOfficerId":-1,"loanId":-1,"clientId":-1,"groupId":-1,"loanType":-1,"reportName":"Loan Disbursed"}', 300, 'Dear {{FullName}}, your loan has been disbursed  Collect your cheque at the group office. {{officeName}}', NULL, NULL, CURDATE(), 1, CURDATE(), 1, NULL, NULL, NULL, NOW(), 1);
