//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.15 at 09:51:17 AM IST 
//

package com.finflux.risk.creditbureau.provider.highmark.xsd.old.response;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="BATCH-ID" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="REQUEST-DT-TM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RESPONSE-DT-TM" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RESPONSE-TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="USER-ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MBR-NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "REPORT-FILE")
public class HighMarkResponse {

    @XmlElement(name = "FILE-SUBMISSION-DETAILS")
    private FileSubmissionDetails FilesubmissionDetails;

    @XmlElement(name = "INQUIRY-STATUS")
    private InquiryStatus inquiryStatus;

    public InquiryStatus getInquiryStatus() {
        return this.inquiryStatus;
    }

    public FileSubmissionDetails getFilesubmissionDetails() {
        return this.FilesubmissionDetails;
    }
}
